### Titanic ###

import numpy

import pandas

import scikit-learn

In [1]:
import numpy as np
from sklearn import tree
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

In [3]:
train_path = "train.csv"
train = pd.read_csv(train_path)

test_path = "test.csv"
test = pd.read_csv(test_path)

In [4]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000         NaN    0.000000   
50%     446.000000    0.000000    3.000000         NaN    0.000000   
75%     668.500000    1.000000    3.000000         NaN    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [6]:
train['Survived'].value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [7]:
train['Survived'].value_counts(normalize = True) * 100

0    61.616162
1    38.383838
Name: Survived, dtype: float64

In [8]:
print(train['Survived'][train['Sex'] == 'male'].value_counts())

0    468
1    109
Name: Survived, dtype: int64


In [9]:
print(train['Survived'][train['Sex'] == 'male'].value_counts(normalize = True) * 100)

0    81.109185
1    18.890815
Name: Survived, dtype: float64


In [18]:
for col in list(train.columns.values):
    print ("Number of missing data on " + col,train[col].isnull().values.sum())

Number of missing data on PassengerId 0
Number of missing data on Survived 0
Number of missing data on Pclass 0
Number of missing data on Name 0
Number of missing data on Sex 0
Number of missing data on Age 177
Number of missing data on SibSp 0
Number of missing data on Parch 0
Number of missing data on Ticket 0
Number of missing data on Fare 0
Number of missing data on Cabin 687
Number of missing data on Embarked 2


In [19]:
train['Child'] = float('NaN')

In [20]:
train.Child[train['Age'] < 18] = 1
train.Child[train['Age'] >= 18] = 0
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Child  
0      0         A/5 21171   7.2500   NaN        S    0.0  
1      0          PC 17599  71.2833   C85        C    0.0  
2      0  STON/O2. 3101282   7.9250   NaN        S    0.0  
3      0            113803  53.1000  C123        S    0.0  
4      0            373450   8.0500   NaN        S    0.0

In [21]:
print(train['Survived'][train['Child'] == 1].value_counts(normalize = True) * 100)

1    53.982301
0    46.017699
Name: Survived, dtype: float64


In [22]:
print(train['Survived'][train['Child'] == 0].value_counts(normalize = True) * 100)

0    61.896839
1    38.103161
Name: Survived, dtype: float64


In [23]:
train['Sex'][train['Sex'] == 'male'] = 0
train['Sex'][train['Sex'] == 'female'] = 1

In [24]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris   0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...   1  38.0      1      0   
2                             Heikkinen, Miss. Laina   1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)   1  35.0      1      0   
4                           Allen, Mr. William Henry   0  35.0      0      0   

             Ticket     Fare Cabin Embarked  Child  
0         A/5 21171   7.2500   NaN        S    0.0  
1          PC 17599  71.2833   C85        C    0.0  
2  STON/O2. 3101282   7.9250   NaN        S    0.0  
3            113803  53.1000  C123        S    0.0  
4            373450   8.0500   NaN        S    0.0

In [25]:
train['Embarked'] = train['Embarked'].fillna('S')

In [27]:
for col in list(train.columns.values):
    print ("Number of missing data on " + col,train[col].isnull().values.sum())

Number of missing data on PassengerId 0
Number of missing data on Survived 0
Number of missing data on Pclass 0
Number of missing data on Name 0
Number of missing data on Sex 0
Number of missing data on Age 177
Number of missing data on SibSp 0
Number of missing data on Parch 0
Number of missing data on Ticket 0
Number of missing data on Fare 0
Number of missing data on Cabin 687
Number of missing data on Embarked 0
Number of missing data on Child 177


In [28]:
train['Embarked'][train['Embarked'] == 'S'] = 0
train['Embarked'][train['Embarked'] == 'C'] = 1
train['Embarked'][train['Embarked'] == 'Q'] = 2

In [29]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris   0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...   1  38.0      1      0   
2                             Heikkinen, Miss. Laina   1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)   1  35.0      1      0   
4                           Allen, Mr. William Henry   0  35.0      0      0   

             Ticket     Fare Cabin Embarked  Child  
0         A/5 21171   7.2500   NaN        0    0.0  
1          PC 17599  71.2833   C85        1    0.0  
2  STON/O2. 3101282   7.9250   NaN        0    0.0  
3            113803  53.1000  C123        0    0.0  
4            373450   8.0500   NaN        0    0.0

In [32]:
train2 = train[['Pclass', 'Sex', 'Age', 'Fare', 'Survived']]
train2.dropna(axis = 0, inplace = True)

print ("Train shape " + str(train.shape))
print ("Train2 shape " + str(train2.shape))

Train shape (891, 13)
Train2 shape (714, 5)


In [33]:
target = train2['Survived'].values
features_one = train2[['Pclass', 'Sex', 'Age', 'Fare']].values

In [34]:
my_tree_one = tree.DecisionTreeClassifier()

In [35]:
my_tree_one = my_tree_one.fit(features_one, target)

In [38]:
feature_list = ['Pclass', 'Sex', 'Age', 'Fare']
importances = my_tree_one.feature_importances_

for k in range(0, len(feature_list)):
    print ("Feature: " + str(feature_list[k]) + " Importance: " + str(importances[k]))

Feature: Pclass Importance: 0.151525063643
Feature: Sex Importance: 0.300512210958
Feature: Age Importance: 0.244403660945
Feature: Fare Importance: 0.303559064454


In [39]:
print(my_tree_one.score(features_one, target))

0.984593837535


In [41]:
for col in list(test.columns.values):
    print ("Number of missing data on " + col,test[col].isnull().values.sum())

Number of missing data on PassengerId 0
Number of missing data on Pclass 0
Number of missing data on Name 0
Number of missing data on Sex 0
Number of missing data on Age 86
Number of missing data on SibSp 0
Number of missing data on Parch 0
Number of missing data on Ticket 0
Number of missing data on Fare 1
Number of missing data on Cabin 327
Number of missing data on Embarked 0


In [42]:
##test.Fare['152'] = test.Fare.median()
test.Fare = test.Fare.fillna(test.Fare.median())
test.Age = test.Age.fillna(test.Age.median())

In [43]:
test['Sex'][test['Sex'] == 'male'] = 0
test['Sex'][test['Sex'] == 'female'] = 1

test['Embarked'] = test['Embarked'].fillna('S')

test['Embarked'][test['Embarked'] == 'S'] = 0
test['Embarked'][test['Embarked'] == 'C'] = 1
test['Embarked'][test['Embarked'] == 'Q'] = 2

In [45]:
for col in list(test.columns.values):
    print ("Number of missing data on " + col,test[col].isnull().values.sum())



Number of missing data on PassengerId 0
Number of missing data on Pclass 0
Number of missing data on Name 0
Number of missing data on Sex 0
Number of missing data on Age 0
Number of missing data on SibSp 0
Number of missing data on Parch 0
Number of missing data on Ticket 0
Number of missing data on Fare 0
Number of missing data on Cabin 327
Number of missing data on Embarked 0


In [46]:
test_features = test[['Pclass', 'Sex', 'Age', 'Fare']].values
print(test_features)

my_prediction = my_tree_one.predict(test_features)

[[3 0 34.5 7.8292]
 [3 1 47.0 7.0]
 [2 0 62.0 9.6875]
 ..., 
 [3 0 38.5 7.25]
 [3 0 27.0 8.05]
 [3 0 27.0 22.3583]]


In [47]:
PassengerId = np.array(test["PassengerId"]).astype(int)
my_solution = pd.DataFrame(my_prediction, PassengerId, columns = ["Survived"])

print(my_solution)
print(my_solution.shape)

my_solution.to_csv("my_solution.csv", index_label = ["PassengerId"])

      Survived
892          0
893          0
894          1
895          1
896          0
897          0
898          1
899          0
900          1
901          0
902          0
903          0
904          1
905          1
906          1
907          1
908          0
909          1
910          1
911          0
912          0
913          1
914          1
915          0
916          1
917          0
918          1
919          1
920          1
921          0
...        ...
1280         0
1281         0
1282         0
1283         1
1284         0
1285         0
1286         0
1287         1
1288         0
1289         1
1290         0
1291         0
1292         1
1293         0
1294         1
1295         1
1296         0
1297         0
1298         0
1299         1
1300         1
1301         1
1302         1
1303         1
1304         0
1305         0
1306         1
1307         0
1308         0
1309         0

[418 rows x 1 columns]
(418, 1)
